[package]
name = "saturn-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
saturn-protocol.workspace = true
crossterm.workspace = true
ratatui.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["io-std"] }

[dev-dependencies]
tempfile.workspace = true
