//! JSON Schema와 TypeScript 생성. `generated/`와 다르면 테스트가 실패한다.

use std::any::TypeId;
use std::collections::HashSet;

use schemars::generate::SchemaSettings;
use serde_json::{Map, Value, json};
use ts_rs::{Config, TS, TypeVisitor};

use crate::envelope::{ClientMessage, ServerMessage};
use crate::rpc::{Notification, Request};

pub const SCHEMA_FILE: &str = "protocol.schema.json";

pub const TYPESCRIPT_FILE: &str = "protocol.ts";

pub fn json_schema() -> String {
    let mut generator = SchemaSettings::draft2020_12().into_generator();
    let client = generator.subschema_for::<ClientMessage>();
    let server = generator.subschema_for::<ServerMessage>();
    let definitions: Map<String, Value> = generator.take_definitions(true);
    let root = json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "Saturn protocol",
        "description": "One JSON-RPC 2.0 message per line over the engine Unix socket.",
        "oneOf": [client, server],
        "$defs": definitions,
    });
    let mut text = serde_json::to_string_pretty(&root).expect("schema value should serialize");
    text.push('\n');
    text
}

/// 큰 정수는 `number`로 쓴다(값이 2^53을 넘지 않는다).
pub fn typescript() -> String {
    let config = Config::new().with_large_int("number");
    let mut collector = Collector {
        config: &config,
        seen: HashSet::new(),
        decls: Vec::new(),
    };
    collector.visit::<ClientMessage>();
    collector.visit::<ServerMessage>();
    // 봉투 안에 펼쳐져 이름이 사라지므로 따로 선언한다.
    collector.visit::<Request>();
    collector.visit::<Notification>();
    collector.decls.sort();

    let mut text = String::from(
        "// Generated by `cargo run -p saturn-protocol --example codegen`. Do not edit.\n",
    );
    for (_, decl) in collector.decls {
        text.push('\n');
        text.push_str("export ");
        text.push_str(&decl);
        text.push('\n');
    }
    text
}

struct Collector<'a> {
    config: &'a Config,
    seen: HashSet<TypeId>,
    decls: Vec<(String, String)>,
}

impl TypeVisitor for Collector<'_> {
    fn visit<T: TS + 'static + ?Sized>(&mut self) {
        if !self.seen.insert(TypeId::of::<T>()) {
            return;
        }
        // 선언 파일 자리가 있는 타입만 선언이 있다.
        if T::output_path().is_some() {
            self.decls
                .push((T::ident(self.config), T::decl(self.config)));
        }
        T::visit_dependencies(self);
    }
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::*;

    fn saved(file: &str) -> String {
        let path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("generated")
            .join(file);
        std::fs::read_to_string(&path).unwrap_or_default()
    }

    #[test]
    fn saved_schema_matches_types() {
        assert!(
            saved(SCHEMA_FILE) == json_schema(),
            "generated/{SCHEMA_FILE} is stale; run `cargo run -p saturn-protocol --example codegen`"
        );
    }

    #[test]
    fn saved_typescript_matches_types() {
        assert!(
            saved(TYPESCRIPT_FILE) == typescript(),
            "generated/{TYPESCRIPT_FILE} is stale; run `cargo run -p saturn-protocol --example codegen`"
        );
    }

    #[test]
    fn typescript_declares_every_root() {
        let text = typescript();

        for name in [
            "ClientMessage",
            "ServerMessage",
            "Request",
            "Notification",
            "ProviderEvent",
            "RpcError",
        ] {
            assert!(text.contains(&format!("export type {name} ")), "{name}");
        }
    }

    #[test]
    fn schema_resolves_every_reference() {
        let text = json_schema();
        let root: Value = serde_json::from_str(&text).unwrap();
        let defs = root["$defs"].as_object().unwrap();

        for reference in text.split("\"$ref\": \"#/$defs/").skip(1) {
            let name = reference.split('"').next().unwrap();
            assert!(defs.contains_key(name), "{name}");
        }
    }
}
